name: Audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/cargo-deny
          key: cargo-deny

      - name: Install cargo-deny
        run: cargo -v install cargo-deny

      - name: Checkout
        uses: actions/checkout@v3

      - name: Audit
        run: |
          cargo xtask audit
